import { StyleSheet } from 'react-native';
import { COLORS, SPACING, BORDER_RADIUS } from '../../constants/theme';
import { createShadow } from '../../utils/shadows';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: COLORS.background,
    },
    scrollView: {
        flex: 1,
    },
    scrollContent: {
        paddingBottom: 100, // Padding masivo solicitado para visualización completa de peleadores
    },
    formContainer: {
        paddingHorizontal: SPACING.lg,
    },
    row: {
        flexDirection: 'row',
        gap: SPACING.md,
    },
    halfWidth: {
        flex: 1,
    },
    loadingContainer: {
        padding: SPACING.xl,
        alignItems: 'center',
        justifyContent: 'center',
    },
    loadingText: {
        marginTop: SPACING.md,
        fontSize: 14,
        color: COLORS.text.secondary,
    },
    validatingText: {
        marginTop: -SPACING.md,
        marginBottom: SPACING.md,
        fontSize: 12,
        color: COLORS.primary,
        fontStyle: 'italic',
        paddingLeft: SPACING.xs,
    },
    photoContainer: {
        alignItems: 'center',
        paddingVertical: SPACING.lg,
    },
    photoWrapper: {
        width: 120,
        height: 120,
        borderRadius: 60,
        borderWidth: 2,
        borderColor: 'rgba(255,255,255,0.1)',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: SPACING.md,
        backgroundColor: COLORS.surface,
        position: 'relative', // Para el overlay
    },
    photoWrapperActive: {
        borderColor: COLORS.primary,
        borderWidth: 3,
        ...createShadow(COLORS.primary, 0, 0, 0.5, 10, 10),
    },
    cardPhotoWrapper: {
        width: 220, // Rectangular 2.2:1 approx
        height: 100,
        borderRadius: BORDER_RADIUS.md,
        borderWidth: 2,
        borderColor: 'rgba(255,255,255,0.1)',
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: SPACING.md,
        backgroundColor: COLORS.surface,
        position: 'relative',
        overflow: 'hidden',
    },
    cardPhotoWrapperActive: {
        borderColor: COLORS.primary,
        borderWidth: 3,
        ...createShadow(COLORS.primary, 0, 0, 0.5, 10, 10),
    },
    photoPreview: {
        width: '100%',
        height: '100%',
        borderRadius: 60,
    },
    photoPlaceholder: {
        width: '100%',
        height: '100%',
        borderRadius: 60,
        alignItems: 'center',
        justifyContent: 'center',
    },
    cameraOverlay: {
        position: 'absolute',
        bottom: 0,
        right: 0,
        backgroundColor: COLORS.primary,
        width: 36,
        height: 36,
        borderRadius: 18,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 2,
        borderColor: '#000',
    },
    photoActions: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: SPACING.md,
        marginTop: SPACING.xs,
    },
    changePhotoText: {
        color: COLORS.primary,
        fontWeight: '600',
        fontSize: 14,
    },
    removePhotoText: {
        color: COLORS.error,
        fontWeight: '600',
        fontSize: 14,
    },
    verticalDivider: {
        width: 1,
        height: 16,
        backgroundColor: 'rgba(255,255,255,0.2)',
    },
    photoHintText: {
        fontSize: 12,
        color: COLORS.text.secondary,
        textAlign: 'center',
        marginTop: SPACING.xs,
        maxWidth: 200,
    },
    actionBtnCircle: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: 'rgba(255,100,100,0.8)', // Un color que resalte, o usar primary
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.2)',
        ...createShadow('#000', 0, 2, 0.3, 3, 3),
    },
    largeIconBtn: {
        alignItems: 'center',
        justifyContent: 'center',
        padding: 10,
        backgroundColor: 'rgba(255,255,255,0.05)',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.1)',
        minWidth: 80,
    },
    largeIconText: {
        marginTop: 8,
        color: COLORS.text.primary,
        fontSize: 10,
        fontWeight: 'bold',
        letterSpacing: 1,
    },
    // ESTILOS PARA MODAL Y SELECTOR DE FOTOS
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.85)',
        justifyContent: 'center',
        alignItems: 'center',
        padding: SPACING.lg,
    },
    modalContent: {
        backgroundColor: COLORS.surface,
        borderRadius: BORDER_RADIUS.lg,
        width: '100%',
        maxWidth: 400,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.1)',
        ...createShadow('#000', 0, 10, 0.5, 20, 10),
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: SPACING.lg,
        borderBottomWidth: 1,
        borderBottomColor: 'rgba(255,255,255,0.1)',
        backgroundColor: 'rgba(255,255,255,0.02)',
        borderTopLeftRadius: BORDER_RADIUS.lg,
        borderTopRightRadius: BORDER_RADIUS.lg,
    },
    modalTitle: {
        fontSize: 16,
        fontWeight: '800',
        color: COLORS.primary,
        letterSpacing: 1,
    },
    imageOptionsContainer: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        padding: SPACING.xl,
        gap: SPACING.xl,
    },
    imageOptionButton: {
        alignItems: 'center',
        justifyContent: 'center',
        gap: SPACING.sm,
    },
    imageOptionIcon: {
        width: 64,
        height: 64,
        borderRadius: 32,
        backgroundColor: 'rgba(255, 215, 0, 0.1)',
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: COLORS.primary,
        marginBottom: 8,
    },
    imageOptionText: {
        color: COLORS.text.primary,
        fontWeight: '600',
        fontSize: 14,
    },
    verticalDividerLarge: {
        width: 1,
        height: 60,
        backgroundColor: 'rgba(255,255,255,0.1)',
        marginHorizontal: SPACING.lg,
    },
    progressContainer: {
        paddingHorizontal: SPACING.lg,
        paddingVertical: SPACING.md,
        backgroundColor: 'rgba(255, 255, 255, 0.05)',
    },
    progressBackground: {
        height: 4,
        backgroundColor: 'rgba(255, 255, 255, 0.1)',
        borderRadius: 2,
        marginBottom: SPACING.sm,
    },
    progressBar: {
        height: '100%',
        backgroundColor: COLORS.primary,
        borderRadius: 2,
    },
    stepsTextContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    stepText: {
        fontSize: 12,
        color: COLORS.text.tertiary,
        fontWeight: '600',
    },
    stepTitle: {
        fontSize: 14,
        color: COLORS.primary,
        fontWeight: '800',
        textTransform: 'uppercase',
    },
    navigationButtons: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: SPACING.xl,
        gap: SPACING.md,
    },
    backButton: {
        flex: 1,
        backgroundColor: 'transparent',
        borderWidth: 1,
        borderColor: COLORS.text.tertiary,
        paddingVertical: SPACING.md,
        borderRadius: 8,
        alignItems: 'center',
        justifyContent: 'center',
    },
    backButtonText: {
        color: COLORS.text.tertiary,
        fontSize: 16,
        fontWeight: '600',
    },
    nextButton: {
        flex: 2,
        backgroundColor: COLORS.primary,
        paddingVertical: SPACING.md,
        borderRadius: 8,
        alignItems: 'center',
        justifyContent: 'center',
        ...createShadow(COLORS.primary, 0, 4, 0.3, 5, 4),
    },
    nextButtonText: {
        color: '#000',
        fontSize: 16,
        fontWeight: '800',
        textTransform: 'uppercase',
    },
});
